version: '3.8'
services:
  db:
    image: postgres:14.1-alpine

    #restart: always
    environment:
      POSTGRES_USER: labib
      POSTGRES_PASSWORD: labib
      POSTGRES_DB: project-manager-labib
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql